from typing import Any

class Graph:
    def add_nodes_from(*args: Any, **kwargs: Any) -> None: ...
    def add_edges_from(*args: Any, **kwargs: Any) -> None: ...

def spring_layout(*args: Any, **kwargs: Any) -> dict[Any, Any]: ...
def draw(*args: Any, **kwargs: Any) -> None: ...
