from typing import Any

class Axes: ...
class Figure: ...

def figure(*args: Any, **kwargs: Any) -> Figure: ...
def scatter(*args: Any, **kwargs: Any) -> None: ...
def xlabel(*args: Any, **kwargs: Any) -> None: ...
def ylabel(*args: Any, **kwargs: Any) -> None: ...
def title(*args: Any, **kwargs: Any) -> None: ...
def show(*args: Any, **kwargs: Any) -> None: ...
